memory-sync: add logging, improvements

diff --git a/.local/bin/memory-sync b/.local/bin/memory-sync
--- a/.local/bin/memory-sync
+++ b/.local/bin/memory-sync
@@ -1,5 +1,5 @@
 #!/bin/sh
-# todo: better arguments
+# todo: better arguments, better signals, better errors
 
 # checks
 command -v rsync >/dev/null 2>&1 || { echo "needs rsync bud. exiting"; exit 1; }
@@ -14,6 +14,7 @@ for arg; do [ -z "$arg" ] && echo 'an argument was empty. exiting' && exit 1; do
 # -d: set offline wait time between syncs for command daemon, set to 0 to disable daemon when offline
 # -D [-e]: launch a daemon, -e to exit on process death (doesn't work with pid)
 # -f: match for full command line for command daemon
+# -n: notify-send on failures
 # -s: <dir>: sync files somewhere else instead of /dev/shm
 # -t: set check time for command daemon
 # -u: set online wait time between syncs for daemon
@@ -23,8 +24,9 @@ for arg; do [ -z "$arg" ] && echo 'an argument was empty. exiting' && exit 1; do
 # [3] (one-shot): how to sync, defaults to auto. can sync to "ram" or "disk"
 
 # defaults
+programName=$(basename "$0")
 timeCheck=5
-tmpDir=/dev/shm/$USER/$(basename "$0")
+tmpDir=/dev/shm/$USER/$programName
 
 # opts
 while true; do
@@ -41,6 +43,7 @@ while true; do
 	}
 	[ "$1" = "-C" ] && { clean=true; shift; continue; }
 	[ "$1" = "-f" ] && { full=true shift; continue; }
+	[ "$1" = "-n" ] && { notify=true shift; continue; }
 	break
 done;
 
@@ -74,7 +77,7 @@ if [ "$daemon" ]; then
 	fi
 	[ "$command" ] && {
 		command -v "$command" || {
-			echo "note: '$command' not found in PATH"
+			echo "note: '$command' not found in PATH" >&2
 		}
 	}
 	if [ "$full" ]; then
@@ -118,15 +121,22 @@ cleanup(){
 	exit
 }
 
+if [ "$notify" ]; then
+	log()( echo "$programName": "$@"; notify-send "$programName" "$@" )
+else
+	log()( echo "$programName": "$@" )
+fi
+
 exiter(){
-	echo 'reached exit' >&2
+	status=$?
 	[ "$daemon" ] && {
-		[ "$daemonPID" ] && killdaemon
+		killdaemon
 	}
 	[ -e "$lockFile" ] && rm -v "$lockFile"
-	exit
+	echo "reached exit"
+	exit $status
 }
-trap 'sync; exit' INT TERM
+trap 'echo killed; exit' INT TERM
 trap exiter EXIT
 
 sync(){
@@ -154,16 +164,21 @@ sync(){
 			ln -vsT "$memDir" "$linkDir"
 		}
 
+		[ -e "$unpackFile" ] && {
+			echo "data in '$tmpDir' already exists"
+			exit 1
+		}
 		rsync -aHAWXv "$staticDir/" "$linkDir" >&2 &&
 			touch "$unpackFile" || {
-			echo "epic fail" && exit 1
+			log "epic fail"
+			exit 3
 		}
 	else
 		echo 'from ram to disk'
 		[ -e "$unpackFile" ] || {
-			echo "cannot sync, nothing in '$tmpDir'."
-			echo "try syncing normally before running the daemon. exiting"
-			exit 1
+			log "cannot sync, nothing in '$tmpDir'."
+			echo "try syncing disk-to-ram before running the daemon."
+			exit 2
 		}
 		[ -e "$lockFile" ] && {
 			echo 'lock in place, waiting for removal...'
@@ -171,13 +186,13 @@ sync(){
 		}
 		touch "$lockFile"
 		rsync -aHAWXv --delete "$linkDir/" "$staticDir" >&2 || {
-			echo 'sync error! exiting'
-					rm -v "$lockFile"
-					exit 1
-				}
+			log 'sync error!'
+			rm -v "$lockFile"
+			exit 3
+		}
 				rm "$lockFile"
 	fi
-	echo
+	echo >&2
 }
 
 if [ ! "$daemon" ]; then
@@ -193,31 +208,32 @@ else
 			}
 		else # launch daemon
 			{
-				trap 'kill -- $watchPID; kill -- $loopPID; exit' TERM INT
+				trap 'kill -- $watchPID; kill -- $loopPID 2>/dev/null; exit' TERM INT
 				{
 					trap 'exit' INT TERM
-					trap 'kill -- $!' EXIT
+					trap 'kill -- "$sleepPID" 2>/dev/null' EXIT
 					while true; do
-						sleep "$1" &
-						wait
-						sync || exit 1
+						[ -d "/proc/$$" ] || exit # additional check
+						sleep "$1" & sleepPID=$!
+						wait $!
+						sync
 					done
 				} & loopPID=$!
 				{
 					{
 						waitpid $$
-						echo 'daemon: parent was murdered, exiting'
+						log 'daemon: parent was murdered'
 						kill $loopPID
 					} & pid=$!
 					{
 						waitpid $loopPID
-						echo 'daemon was killed, exiting'
+						log 'daemon was killed'
 						kill $$
 					} & pid="$pid $!"
-					trap 'kill $pid' INT TERM
+					trap 'kill $pid 2>/dev/null' INT TERM
 					wait
 				} & watchPID=$!
-				while true; do wait && break; done
+				while true; do wait && break; done # recieve signals
 			} & daemonPID=$!
 		fi
 	}
@@ -230,7 +246,7 @@ else
 
 	if [ "$command" ]; then
 		# track by command name
-		echo "watching '$command' command"
+		first=true
 		while true; do
 			if pgrep -x "$command" >/dev/null; then
 				[ "$up" ] || echo "'$command' is up"
@@ -242,7 +258,7 @@ else
 				wait $!
 
 			else
-				[ "$up" ] && echo "'$command' is down"
+				[ "$up" ] || [ "$first" ] && echo "'$command' is down"
 				if [ "$exitDown" ]; then # exit
 					if [ "$exitCheck" ]; then # wait
 						echo "'$command' not running, waiting once"
@@ -266,6 +282,7 @@ else
 				sleep "$timeCheck" &
 				wait $!
 			fi
+			unset first
 		done
 	elif [ "$pid" ]; then
 		# track via waitpid
